CREATE DATABASE SafariZone

CREATE TABLE Roles (
    RoleId INT IDENTITY PRIMARY KEY,
    RoleName NVARCHAR(50) NOT NULL UNIQUE, -- Admin, Employee, Tourist
    Description NVARCHAR(255)
);

CREATE TABLE Users (
  UserId INT PRIMARY KEY IDENTITY(1,1),
  Email VARCHAR(100) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(RoleId),
  IsActive BIT DEFAULT 1,
  LastLogin DATETIME,
  CreatedAt DATETIME DEFAULT GETDATE(),
  UpdatedAt DATETIME DEFAULT GETDATE()
);


ALTER TABLE Users
alter column AadId NVARCHAR(256) NULL

SELECT * from roles