CREATE DATABASE SafariZone

CREATE TABLE Roles (
    RoleId INT IDENTITY PRIMARY KEY,
    RoleName NVARCHAR(50) NOT NULL UNIQUE, -- Admin, Employee, Tourist
    Description NVARCHAR(255)
);

CREATE TABLE Users (
  UserId INT PRIMARY KEY IDENTITY(1,1),
  Username VARCHAR(50) NOT NULL UNIQUE,
  Email VARCHAR(100) NOT NULL UNIQUE,
  PhoneNumber VARCHAR(20),
  PasswordHash VARCHAR(255) NOT NULL,
  RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(RoleId),
  IsActive BIT DEFAULT 1,
  LastLogin DATETIME,
  CreatedAt DATETIME DEFAULT GETDATE(),
  UpdatedAt DATETIME DEFAULT GETDATE()
);

